# ----------- CONFIGURABLE START -----------
title:            "LiberXue|FullStack|Developer|jekyll blog|GitHub blog"
description:      "Full Stack"
url:              https://liberxue.github.io # 域名
signoff:          "LiberXue" # Your name
facebook_appid:   #liberxue
google_analytics: UA-101222464-1
share:            true 
# Pages
paginate: 15
paginate_path: "liberxuepage:num"
gems: [jekyll-paginate]
links:
  - name:         Home
    url:          /
    external:     false
  - name:         Book
    url:          /book
    external:     false
  - name:         Road
    url:          /road
    external:     false
  - name:         Archives
    url:          /archives
    external:     false
  - name:         Tags
    url:          /tags
    external:     false
  - name:         About
    url:          /about
    external:     false
# ------------ CONFIGURABLE END ------------

#permalink:        /:categories/:title.html
permalink: /:year/:month/:day/:title.html
defaults:
  - values:
      layout: "default"
